# Generated by Django 6.0.6 on 2026-06-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('tests', models.IntegerField(default=0)),
                ('parameters', models.IntegerField(default=0)),
                ('fasting', models.CharField(default='Required', max_length=100)),
                ('reports', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('popular', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
