# Generated by Django 6.0.6 on 2026-06-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_healthpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpackage',
            name='reports_time_hours',
            field=models.IntegerField(default=24),
        ),
    ]
