# Generated by Django 6.0.6 on 2026-06-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_healthpackage_reports_time_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpackage',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='healthpackage',
            name='aliases',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='healthpackage',
            name='identifies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='healthpackage',
            name='interpretations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='healthpackage',
            name='measures',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='healthpackage',
            name='prep',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='healthpackage',
            name='why',
            field=models.TextField(blank=True, default=''),
        ),
    ]
