# Generated by Django 6.0.6 on 2026-06-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_healthpackage_about_healthpackage_aliases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='test',
            name='aliases',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='test',
            name='fasting',
            field=models.CharField(default='Not Required', max_length=100),
        ),
        migrations.AddField(
            model_name='test',
            name='identifies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='test',
            name='interpretations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='test',
            name='measures',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='test',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='test',
            name='parameters',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='test',
            name='prep',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='test',
            name='reports',
            field=models.CharField(default='12 hours', max_length=100),
        ),
        migrations.AddField(
            model_name='test',
            name='why',
            field=models.TextField(blank=True, default=''),
        ),
    ]
